#ifndef HOBBITSPYTHON_GLOBAL_H
#define HOBBITSPYTHON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HOBBITSPYTHON_LIBRARY)
#  define HOBBITSPYTHONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HOBBITSPYTHONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HOBBITSPYTHON_GLOBAL_H
