#ifndef FINDANALYZER_GLOBAL_H
#define FINDANALYZER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined (FINDANALYZER_LIBRARY)
#  define FINDANALYZERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FINDANALYZERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FINDANALYZER_GLOBAL_H
