#ifndef HOBBITSWIDGETS_GLOBAL_H
#define HOBBITSWIDGETS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HOBBITSWIDGETS_LIBRARY)
#  define HOBBITSWIDGETSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HOBBITSWIDGETSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HOBBITSWIDGETS_GLOBAL_H
