#ifndef FWD_ABSTRACTPARAMETEREDITOR_H
#define FWD_ABSTRACTPARAMETEREDITOR_H

#include "hobbits-core_global.h"

class HOBBITSCORESHARED_EXPORT AbstractParameterEditor;

#endif // FWD_ABSTRACTPARAMETEREDITOR_H
